# Numpy Introduction

In [1]:
import numpy as np

In [2]:
np.array([4,5,67,8,2,34,78,2])

array([ 4,  5, 67,  8,  2, 34, 78,  2])

In [3]:
np.array([4,5,67,8,2,34,78,2,'hello'])

array(['4', '5', '67', '8', '2', '34', '78', '2', 'hello'], dtype='<U11')

In [4]:
np.array([4,5,67,8,2,34,78,2,True])

array([ 4,  5, 67,  8,  2, 34, 78,  2,  1])

In [5]:
# range()
# np.arange(start,stop,step)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
a = 12
b = 33

In [9]:
c = a + b
print(c)

45


In [11]:
print(dir(list))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [13]:
np.arange(21,1,-1)

array([21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,
        4,  3,  2])

In [14]:
# linear space
# it is returning 50 elements with equal step
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [16]:
np.linspace(1,10,num=20, retstep=True)

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [17]:
np.arange(-21,1)

array([-21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,
        -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [18]:
np.arange(21,1,-1)

array([21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,
        4,  3,  2])

In [19]:
np.random.randint(1,10)

8

In [20]:
np.random.randint(1,10,10)

array([4, 8, 1, 2, 7, 9, 8, 6, 6, 3])

In [21]:
np.random.randint(1,10,(5,5))

array([[2, 9, 4, 2, 5],
       [7, 4, 2, 8, 5],
       [6, 4, 4, 4, 8],
       [4, 5, 9, 4, 9],
       [9, 8, 3, 8, 7]])

In [22]:
x = np.random.randint(1,10,(5,5))

In [26]:
x

array([[9, 6, 5, 3, 7],
       [7, 1, 2, 3, 7],
       [9, 7, 9, 3, 4],
       [7, 2, 5, 9, 8],
       [8, 7, 7, 8, 8]])

In [27]:
x[0]

array([9, 6, 5, 3, 7])

In [31]:
np.random.seed(2)
np.random.randint(1,10)

9

In [32]:
x[2]

array([9, 7, 9, 3, 4])

In [33]:
x[0:2]

array([[9, 6, 5, 3, 7],
       [7, 1, 2, 3, 7]])

In [34]:
x[0:2,0:2]

array([[9, 6],
       [7, 1]])

In [35]:
x[:, 0:2]

array([[9, 6],
       [7, 1],
       [9, 7],
       [7, 2],
       [8, 7]])

In [36]:
x

array([[9, 6, 5, 3, 7],
       [7, 1, 2, 3, 7],
       [9, 7, 9, 3, 4],
       [7, 2, 5, 9, 8],
       [8, 7, 7, 8, 8]])

In [37]:
# convert 2d array to 1d array
x.flatten()

array([9, 6, 5, 3, 7, 7, 1, 2, 3, 7, 9, 7, 9, 3, 4, 7, 2, 5, 9, 8, 8, 7,
       7, 8, 8])

In [38]:
x = np.random.randint(1,10,(5,4))

In [39]:
x

array([[9, 7, 3, 9],
       [8, 3, 2, 6],
       [5, 5, 6, 8],
       [4, 7, 5, 4],
       [8, 7, 2, 4]])

In [40]:
x.shape

(5, 4)

In [41]:
x.reshape(4,5)

array([[9, 7, 3, 9, 8],
       [3, 2, 6, 5, 5],
       [6, 8, 4, 7, 5],
       [4, 8, 7, 2, 4]])

In [42]:
x.reshape(-1,10)

array([[9, 7, 3, 9, 8, 3, 2, 6, 5, 5],
       [6, 8, 4, 7, 5, 4, 8, 7, 2, 4]])

In [43]:
x.reshape(4,-1)

array([[9, 7, 3, 9, 8],
       [3, 2, 6, 5, 5],
       [6, 8, 4, 7, 5],
       [4, 8, 7, 2, 4]])